### ISSUE TITLE
Does not process fluids from fluid tank

### ISSUE THREAD

**Issue by sp823** [jakimfett/Minechem#554]
If I connect an enderIO fluid conduit to the top of the machine, the fuild tank on the decomposer fills with 5000mb of carbon, but nothing happens. It works if you manually bucket it in (which decomposes the bucket as well).

**Comment by way2muchnoise** [comment]
@sp823 I guess the fluid is not registered to have a recipe while the bucket probably gets reverse engineered. Try using MT or suggest a recipe.

**Comment by jakimfett** [comment]
I think this might have been related to #557. @sp823, could I get you to test the latest RC on CurseForge?

**Comment by hilburn** [comment]
I don't this it's related to that Issue - I don't think we add recipes for decomposing our own fluids because.. they're already decomposed

**Comment by hilburn** [comment]
fixed in #571

**Comment by jakimfett** [comment]
I think we need to do some additional work on this. Right now, unless it's in test tube form, you can't actually use chemicals (might be able to use buckets actually, I forgot to check). 

My thought being...we could check if it's a chemical drum, and if so, attempt to pull fluid from it, couldn't we?

**Comment by hilburn** [comment]
ermmm we could handle it specially, but in general, nope, it's stored as NBT in the itemstack

**Comment by jakimfett** [comment]
Bah. They should use fluid tanks in their items.
