### ISSUE TITLE
Decomposer recipes vanished?!

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [jakimfett/Minechem#557]
I used to be able to decompose all the iron, leather, gold armor, weapon and tools. Now I can't. Neither can I decompose slabs, and brick block/slabs.

Even Thaumcraft stuff isn't possible to decompose anymore, like the mundane belts and amulets.

In fact lots of recipes don't work anymore. What'sgoping on?

**Comment by way2muchnoise** [comment]
@Unrepentant-Atheist Pics or it didn't happen. Also read the [Bug Reporting Guidelines](https://github.com/jakimfett/Minechem/wiki/Bug-Reporting) before posting bug reports.

**Comment by Unrepentant-Atheist** [comment]
Pics of what? How I can't put stuff into the decomposer? That'd be just a screenshot of me with an open inventory and decomposer and stuff that's put in the slot and doing nothing.

**Comment by jakimfett** [comment]
Yeah, I mis-clicked on the enhancement thing. Just ignore that.

@way2muchnoise I just tested this, and @Unrepentant-Atheist is right...you can't decompose tools anymore, even freshly crafted (undamaged) tools/weapons.

**Comment by Unrepentant-Atheist** [comment]
Y'all be the best! Works now with the latest build!

**Comment by jakimfett** [comment]
Awesome. I pushed a new RC to CurseForge with the fix for this...thanks for reporting this!
