### ISSUE TITLE
Designer drugs.

### ISSUE THREAD

**Issue by Shuudoushi** [jakimfett/Minechem#564]
I'd like to have just what the title implies, designer drugs. I don't think it would be hard to implement, as you can just reuse how lacing weapons and the such works, but added to a pill/syringe/empty vile/ect.

Should make for some good old fashion fun on SMP servers as well!

**Comment by hilburn** [comment]
You can use minetweaker to add effects to any molecule in the game, as well as generate new molecules to represent new drugs

**Comment by jakimfett** [comment]
Use Minetweaker if you want more drugs.
