### ISSUE TITLE
Mekanism Compatibility

### ISSUE THREAD

**Issue by SubjectEleven** [jakimfett/Minechem#569]
So, I recently download the latest version of MineChem, and to power the Machines I downloaded Mekanism as well(since they have Generators). But as soon as I started Minecraft I got the following crash report:

http://pastebin.com/xay0nT07

So something is wrong with the compatibility(although I do not know at which end, probably MineChem, because I have the same with Thermal Expansion)

**Comment by jakimfett** [comment]
The issue isn't a compatibility thing. You need to update your mods. One of them is using an outdated version of the Mekanism API. This isn't something we can fix, it's not even related to Minechem.

Please read through the [Mod Reporting Guidelines](https://github.com/jakimfett/Minechem/wiki/Bug-Reporting) before opening another issue.
