### ISSUE TITLE
Issue loading with Reika's mods

### ISSUE THREAD

**Issue by Aulton** [jakimfett/Minechem#570]
It seems your order specifies a loop between Reika's mods. I tried ChromaticCraft, ElectricCraft, Dragon API and RotaryCraft to RR3, which has your mod in it, and it caused me to get this error. http://puu.sh/e67ml/3bb97aab96.png

I made a post on the FTB subreddit and one of the responses suggested me reporting this issue to you.

**Comment by way2muchnoise** [comment]
@Aulton Are you sure you have the latest versions of both minechem and Reika's

**Comment by Aulton** [comment]
I'm using whatever version comes with RR3 mainline of minechem, and I'm sure it's the latest version of Reika's mods. I'll download the latest minechem to make sure, however.

**Comment by Aulton** [comment]
Just confirmed. Seems like the version that was included with RR3 mainline was just outdated. Pardon me for bothering you with this, heh. Guess you fixed it somewhere between that version and your latest.

**Comment by jakimfett** [comment]
No problem, I'll poke the RR guys about updating.

**Comment by jakimfett** [comment]
I talked to Nero, he said he'll include the updated Minechem version in his next release.
