### ISSUE TITLE
RecipeAPI

### ISSUE THREAD

**Issue by Peteka** [jakimfett/Minechem#575]
I don't understate how the RecipeAPI works.
Do I have to add "mods.Minechem.RecipeAPI." like you have to do it in Modtweaker?
Do I have to give the full name (mod:item) in the recipe an add these brackets "<>"?

The example for what I’m trying to do:
RecipeAPI.addSynthesisRecipe(ore:itemSilicon, true, 500, "", "", "", "", "1 Si", "", "", "", "");
or
RecipeAPI.addSynthesisRecipe(<EnderIO:itemMaterial>, true, 500, "", "", "", "","<minechem:minechemElement:14>", "", "", "", "");

Please add these aspects to the wiki page.

Sorry for my bad English.

**Comment by way2muchnoise** [comment]
@Peteka You mean the MT scripts because you can find examples for that at https://github.com/jakimfett/Minechem/blob/master/scripts/Minetweaker.zs

Or do you mean the API for mods

**Comment by Peteka** [comment]
Thank you, the script helped me alot to understand the API.

But I realy think you (or maybe someone else) should add a hint that you have to write first "import mods.minechem.[object]" for noobs like me.

**Comment by jakimfett** [comment]
Unless I'm mistaken, every single other mod with MineTweaker support requires you to import the appropriate classes. Minechem has the example script, but we don't cover the basics of how to modify mods in it. 

Please go read through the MineTweaker wiki, specifically the sections on working with Forge mods, as it'll help you understand how to use MineTweaker.
