### ISSUE TITLE
Blacklist 

### ISSUE THREAD

**Issue by keato14** [jakimfett/Minechem#578]
is there any way i could disable the blacklist

**Comment by jakimfett** [comment]
Did you try removing everything from the blacklist?

**Comment by keato14** [comment]
Yes and everything just came back after I started the game back up

**Comment by jakimfett** [comment]
I just tested this in the latest build...removing things from the blacklist works fine, and the blacklist doesn't reset. Please update to the latest release from CurseForge, and then (if you're still having the issue, please provide the information required in the [Bug Reporting Guidelines](https://github.com/jakimfett/Minechem/wiki/Bug-Reporting).

**Comment by keato14** [comment]
thanks

**Comment by jakimfett** [comment]
Did updating fix your problem?

**Comment by keato14** [comment]
im not on my personal computer right now

**Comment by keato14** [comment]
i will try when i get home

**Comment by jakimfett** [comment]
Closing due to a lack of response from @keato14
