### ISSUE TITLE
Gregtech dusts; Decomposing and Synthesizing

### ISSUE THREAD

**Issue by JasonMcRay** [jakimfett/Minechem#583]
It has been brought to my attention that most of the GregTech dusts are returning Cellulose inside the Chemical Decomposser. I was going to add a Minetweaker scripts for them... but there is A LOT... Is there something there can be done about it, or should I just blacklist the GT dusts from decomposing?

Also I am unable to use synthesizer to get any of GT dusts.

Minechem version: build 369
GT: 5.07.07

**Comment by jakimfett** [comment]
At one point, we tried to implement GregTech dust stuffs, but GT makes so many changes that it just isn't easily possible, especially as GT continues to change.

We've provided MineTweaker integration, so if GT dust support is essential, you can make the changes yourself.
