### ISSUE TITLE
Compressed Theobromine

### ISSUE THREAD

**Issue by whtvr666** [jakimfett/Minechem#584]
Hi, I've been playing ME^4 and in the quests it requires you to make compressed theobromine (and even more compressed after that) but the recipe for it is 100 theobromine in a single spot, which is not possible
Not sure if it's your doing or did parcel change the recipe for ME^4, but since he doesn't respond on the forum and someone advised to suggest the issue here so that's what I do

Also something else - When I was powering up the fussion reactor, left the area and then came back, when I opened it up it showed that it was getting power really fast, when it was actually at 100% (putting two elements into it to combine made the power show properly)

**Comment by way2muchnoise** [comment]
@whtvr666 the compressed theobromine is a custom molecule from ME and I do think having 100 in one place works but should check that.

**Comment by hilburn** [comment]
I think you are able to stack things infinitely in the fake slots, you then just have to put a stack + 36 in the input slots
