### ISSUE TITLE
Transposed Hydrogen into an OpenBlocks tank, and now I can't get it anywhere useful

### ISSUE THREAD

**Issue by Redlazer** [jakimfett/Minechem#587]
I have several mods installed in my private server modpack, including Galactcicraft, Mekanism and EnderIO, and I cannot figure out any way to get the Hydrogen out of storage, and into some useful mechanism, like a gas generator or what have you. This makes me sad. Am I missing something? Perhaps a gas burning generator could be introduced? Or maybe gas/pipe/storage compatibility improved?

Thanks for letting me know if I'm missing anything!

**Comment by jakimfett** [comment]
You'll need to pump it into a decomposer, and then you can (I believe) burn the result in a furnace (if we've given hydrogen a furnace value...can't remember if we did or not, I know we did for cellulose...).

It's...not completely logical, I know. We're completely redesigning the system for v6, making it a bit less...tweaky...to use.

**Comment by jakimfett** [comment]
Closing due to lack of additional user feedback or questions.
