### ISSUE TITLE
Multiple tires of composers/decomposers

### ISSUE THREAD

**Issue by jpastuszek** [jakimfett/Minechem#588]
It feels to easy to build devices that can do such powerful things like synthesis of ender pearl or a diamond. It would be cool if current devices would be split into multiple devices that each can deal with different types of chemicals so that you would need to build them all to make diamond or ender pearl.

**Comment by jakimfett** [comment]
That's actually what v6 is going to deal with. We're doing a complete rewrite of the mod, while keeping the core concept of chemistry.

If you want to see what we're planning to do, take a look at the [design doc for v6](https://docs.google.com/document/d/1uXsfS1Hha_OZFty28qCrWZqVlZOMVQdfGS97JSHTsos/edit?usp=sharing). Keep in mind...this is subject to change as we start fleshing things out.

**Comment by natedogith1** [comment]
Is that document supposed to be open to the public? because it isn't...

**Comment by jakimfett** [comment]
Sorry, at the moment, it's only open to developers and [Patreon supporters](https://www.patreon.com/bePatron?u=94546&patAmt=7.00). I've edited my comment to reflect this...my bad.

**Comment by jpastuszek** [comment]
That is all right. Thanks for the update and for this cool mod. I will be looking forward to version 6 releases.
