### ISSUE TITLE
Suggestion: Chemical Canisters

### ISSUE THREAD

**Issue by AppleConnoiseur** [jakimfett/Minechem#589]
Ever got a huge amount of chemicals you never used in Minechem 5 like Hydrogen and Oxygen? A solution would be to store them in a fancy looking tank block that works like a barrel from JABBA or the Railcraft multi-block tank.

Implementation wise it could use a model and just scale it up exponentially if it is in a size 2 x 2 x 3.

![Chemical Canister](http://rainbow-containers.com/fileadmin/container-bilder/tankcontainer/tankcontainer-1.jpg)

**Comment by jakimfett** [comment]
I don't think we're going to add tanks for Minechem, at least not in the conventional sense. There are so many mods out there that add tanks of some sort (Thermal Expansion, OpenBlocks, Buildcraft, Railcraft, the list goes on...) that there's no reason for Minechem to do its own implementation of tanks.

We're going to use standard the Forge fluid registry, so any mod that adds tanks will let you store Minechem fluids. There's also going to be internal storage of fluids for the machines that use or produce fluids, so you won't need to use pipes or buckets for small amounts of fluids.
