### ISSUE TITLE
Possible NEI bug or Minechem, not sure.

### ISSUE THREAD

**Issue by Froznic** [jakimfett/Minechem#590]
When pressing 'u' to see what you can craft with basalt bricks.  When I scroll right to the chemical decomposer machine.  The game freezes when it gets to that page.  As if it's trying to loop through the list of all the items you can craft with chemical decomposer to find that specific recipe.  But as it does, it seems to be in an endless loop or something because it just sits there.  I waited 5 mins to make sure it just wasn't going really slow but there appears to be some problem somewhere.  Not sure how to debug minecraft to see exactly where the problem is but hopefully the same problem will happen to you.  I'm using the resonant rise pack through at launcher (latest version).  Minecraft 1.7.10.

**Comment by way2muchnoise** [comment]
@Froznic What version of Minechem is it using?

**Comment by Froznic** [comment]
MINECHEM-1.7.10-5.0.5.358

**Comment by way2muchnoise** [comment]
@Froznic  Try manually installing the [latest version form Jenkins](http://jenkins.jakimfett.com/job/Minechem%201.7%20v5/)

**Comment by Froznic** [comment]
Any chance of it corrupting my world?  I have a couple of the machines down but other than that, not much else.

**Comment by way2muchnoise** [comment]
@Froznic I don't think so but backup it up anyway ^^

**Comment by Froznic** [comment]
Bad news :(  Still crashes.

**Comment by way2muchnoise** [comment]
@Froznic Try running it with Debug on in the minechem config and post the log

**Comment by Froznic** [comment]
Any idea where the log would be located?  Also, does this setting need to be changed on the server side too?  (I can do that, just seeing if it's necessary).

**Comment by Froznic** [comment]
@way2muchnoise Well that's interesting.  The log file fml-client-latest.log gains about 5~ MB per second when it crashes.  The current log file is 474MB when I forced minecraft to close.  I'll try and close it sooner to get the tail end of that log.

**Comment by way2muchnoise** [comment]
@hilburn this is one for you
also @Froznic use markdown when posting code makes it easier to read

**Comment by hilburn** [comment]
Ok I can't get this error to occur. Basalt bricks from BluePower? @Froznic

**Comment by Froznic** [comment]
ProjectRed-Exploration

**Comment by jakimfett** [comment]
@Froznic can I get you to test this with the latest build from the [Minechem Jenkins build server](http://jenkins.jakimfett.com/job/Minechem 1.7 v5/)?

**Comment by Froznic** [comment]
@jakimfett Still crashes.

**Comment by Froznic** [comment]
@jakimfett Do I need to be updating NEI as well off of the jenkins build server?

**Comment by way2muchnoise** [comment]
@Froznic Use at least version (1.0.3.62)[http://chickenbones.net/Pages/links.html] since that is what we build against

**Comment by jakimfett** [comment]
@Froznic my build server has NER (Not Enough Resources), not NEI. Completely different (though related) mods.

**Comment by Froznic** [comment]
@way2muchnoise @jakimfett 
K I'm using 1.0.4.83 of NEI.  I also tested the latest build you guys did like 20 mins ago, I don't think any of the stuff you changed was related to this problem but I tried it anyway with no luck.  Still crashes at the same point.  It's not a big deal but it might be if there's more items that are causing it to crashing.  Resonant Rise 3 is also gaining popularity with the AT Launcher.  There might be other items that cause the game to crash doing the same thing I'm doing.  That was just the first one I ran into.

**Comment by jakimfett** [comment]
@Froznic alrighty, at this point, what I need from you is step by step instructions on how to reproduce this, using **only** Minechem and Project Red (ideally just Project Red core and the one module effected by this).

I need all the info you can give me, I'd highly recommend looking through the Bug Reporting Guidelines [Basic Requirements](https://github.com/jakimfett/Minechem/wiki/Bug-Reporting#basic-requirements) section, and providing as detail as possible.

**Comment by Froznic** [comment]
[[ Steps to Reproduce the Crash ]]

Download AT Launcher, install latest version (I have 3.2.2.1 of the launcher)
http://www.atlauncher.com/downloads

Goto packs in the launcher and create a new instance of resonant rise mainline.

Version to install: 3.2.2.1-RC-MAIN (the one that's already selected)

Click Install.

Mods to choose:

Click the Clear All button at the bottom.  

Check Minechem and click install.

There are various required mods auto selected on the left.

Before we launch the game, go into your install directory (click open folder on the instance in at launcher)

Go into config -> minechem.cfg and turn debug on

Now goto the instances tab on the right and click play on the instance you created

Create a new single player world

Game mode survival, more world options -> allow cheats on (so we can grab a block and put it in inventory if we need to)

Create new world

Once in game, press e, wait for the silly fireworksand achievement to disappear

Type in basalt in the search and right click on basalt brick

Now press the right arrow over until you get to the chemical decomposer

This makes the game crash for me, though the sound is still playing??  Must be on it's own process.

At this point the game is not responding and I force it to close.

[[ LOG ]]
This is the tail end of the log file, fml-client-latest.log
5.0.5.358 log
http://pastebin.com/KTbRiCiB

5.0.5.375 log
http://pastebin.com/2PJ0cDKh

If you need more of the logs let me know.  Pastebin has a limit but I could just upload the log file somewhere.

[[ Version Info ]]
This was tested on both MINECHEM-1.7.10-5.0.5.358.jar and Minechem-1.7.10-5.0.5.375.jar
Though, when I updated to 1.7.10-5.0.5.375 I got an error loading my world that said
Forge Mod Loader detected missing blocks/items.   There are 3 missing blocks and items in this save.

Missing blocks/Items:
minecham:fluid.aspartate.name
minechem:minechemBucket.molecule.aspartate
minechem:fluid.aspartate.name

Pretty sure this isn't a big deal, and I clicked yes to continue and the crash happens again
when right clicking basalt bricks and going to chemical decomposer.

[[ More Info ]]
I can zip my world up and share it somewhere if you don't have any luck reproducing this on your own.

**Comment by jakimfett** [comment]
One last question, @Froznic...are you able to reproduce this with *just* NEI, Project Red, and Minechem (in the vanilla launcher, using the latest Forge version? Or does it only happen with the AT Launcher and the RR pack?

**Comment by Froznic** [comment]
Wow that took a lot longer than I would have liked... Anyway, after installing Forge (which took a little bit to figure out) and then installing the mods which I was trying to do it all wrong for about an hour...  I finally got everything working the way you wanted and it still crashes.  Here's the log file:

http://www.filedropper.com/fml-client-latest

Using NEI 1.0.4.83
CodeChicken 1.0.4.29 (required for NEI)
ProjectRed 4.5.8.59-Base
ProjectRed 4.5.8.59-Compat
ProjectRed 4.5.8.59-World
and the latest Forge version

**Comment by jakimfett** [comment]
Awesome, thank you so much @Froznic! That's exactly what I needed.

**Comment by jakimfett** [comment]
@Froznic could I get you to grab the latest build from the [Minechem Jenkins build server](http://jenkins.jakimfett.com/job/Minechem%201.7%20v5/) and let me know if this still happens for you?

**Comment by jakimfett** [comment]
Closing due to lack of response from @Froznic.
