### ISSUE TITLE
MineChem Inventory crash

### ISSUE THREAD

**Issue by StuardBr** [jakimfett/Minechem#592]
Hello! I'm here to report a crash with the MineChem.

What's happening?
I create a new world, in creative (Or set gamemode to creative in a existent world). When i go to creative inventory and click on the "Search" tab, the game crash.
Tested with and without NEI and the crash persist.
The issue is only in creative mode. Survival inventory and NEI Search on survival is OK.

Versions:
Forge 10.13.2.1263 (Unable do update due to Gregtech incompatibility)
MineChem 1.7.10-5.0.5.358 / 1.7.10-5.0.5.369

CrashLog: http://pastebin.com/s16kuCAn

Tks for the atention :)

**Comment by jakimfett** [comment]
@StuardBr, this should be fixed in the [latest builds](http://jenkins.jakimfett.com/view/ForgeModding/job/Minechem%201.7%20v5/), could I get you to test it?

**Comment by StuardBr** [comment]
Thank you very much! Is working like a charm now. If i find anything else, i open a new issue. Thanks again :)

Fixed

**Comment by jakimfett** [comment]
Awesome!
