### ISSUE TITLE
Fluid recipes with Minetweaker not working

### ISSUE THREAD

**Issue by parcel31u** [jakimfett/Minechem#596]
val liquidWater = <fluid:water>;

Decomposer.removeFluid(liquidWater*1000);

Gives an error of http://pastebin.com/yTdRtbhy

using version 370

**Comment by hilburn** [comment]
should be <fluid:water>

**Comment by jakimfett** [comment]
@parcel31u, can I get you to confirm that this is fixed in the [latest builds](http://jenkins.jakimfett.com/view/ForgeModding/job/Minechem%201.7%20v5/)?

**Comment by parcel31u** [comment]
fixed

**Comment by jakimfett** [comment]
Awesome!
