### ISSUE TITLE
Recipe Conflicts - Aspartate

### ISSUE THREAD

**Issue by parcel31u** [jakimfett/Minechem#597]
Both Aspartate and Aspartic Acid have the same sythesis recipe of C4H7NO4 which I fixed with minetweaker by using 

Synthesiser.removeRecipe(<minechem:minechemMolecule:41>);	
Synthesiser.addRecipe([<minechem:minechemElement:6> * 8,<minechem:minechemElement:1> * 14, <minechem:minechemElement:7> * 2,<minechem:minechemElement:8> * 8],<minechem:minechemMolecule:41>*2,false,100);		

Which just double the input and output for one of them. This is of somewhat importance since it's needed to make melons. It's not a problem for me, but for anyone who adds the mod to their game, they'll have the problem.

**Comment by parcel31u** [comment]
Using version 370

**Comment by jakimfett** [comment]
Latest versions should have fixed this.
