### ISSUE TITLE
RF API

### ISSUE THREAD

**Issue by hilburn** [jakimfett/Minechem#599]
I'm gonna do some tidying up of MinechemTileEntityElectric at some point because.. it's not right

Firstly: https://github.com/CoFH/CoFHLib/blob/master/src/main/java/cofh/api/energy/IEnergyStorage.java#L5

Secondly we should be using IEnergyReceiver not IEnergyHandler

Thirdly it breaks without the CoFH api present.

Don't have time now, but I will

**Comment by jakimfett** [comment]
When you do that, any chance you could set up the basic RF stuffs in the v6 prefab?

**Comment by jakimfett** [comment]
Thanks so much @hilburn, the v6 stuff looks awesome!
