### ISSUE TITLE
Cannot shift click elements into bottom row of the decomposer 

### ISSUE THREAD

**Issue by parcel31u** [jakimfett/Minechem#604]
Using 372

**Comment by way2muchnoise** [comment]
@parcel31u One day I'll fix it

**Comment by parcel31u** [comment]
okay XD

**Comment by way2muchnoise** [comment]
@parcel31u Do note it was the Synth having shift problems not the decomp. But guess what today was the day ^^

**Comment by jakimfett** [comment]
Thanks for the fix, @way2muchnoise. If you have issues with this with the latest builds, go ahead and open a new issue @parcel31u.
