### ISSUE TITLE
Cannot Add recipes for fluids

### ISSUE THREAD

**Issue by parcel31u** [jakimfett/Minechem#605]
Removing fluid recipes works, but I think the adding part was forgotten about.

Tried both: 

Decomposer.addFluid(liquidWater*1000,[H*10, water*10]);

and 

Decomposer.addRecipe(liquidWater*1000,[H*10, water*10]);

**Comment by jakimfett** [comment]
@parcel31u could I get you to test this in the [latest build](http://jenkins.jakimfett.com/view/ForgeModding/job/Minechem%201.7%20v5/)?

**Comment by parcel31u** [comment]
works

**Comment by jakimfett** [comment]
Thanks for letting me know!
