### ISSUE TITLE
Journal not setting recipe in synthesizer, build 375

### ISSUE THREAD

**Issue by StrangeThistle** [jakimfett/Minechem#610]
While the journal was working fine in earlier builds, I have not been able to use it to set the recipe in the synthesizer in builds 369, 374, or 375. (single player game in the ME4 modpack) This video demonstration was made using build 374.
http://youtu.be/iqyhkD35FS8

I have created a new instance in MultiMC (forge 10.13.2.1300) with Minechem-1.7.10-5.0.5.375, CoFHCore-[1.7.10]3.0.0B9-126, & EnderIO-1.7.10-2.2.6.317. In attempting to test the journal in this environment in a single player, superflat world, I get a crash that I don't get in the ME4 pack.

http://pastebin.com/wxmv7hWX (minecraft log, the fml-client-latest log is too big for me to post on pastebin, since MultiMC seems to generate several logs, let me know if there is a better 1 to post)

http://pastebin.com/mTyS1f2W (minecraft crash report)

To reproduce the crash, open the synthesizer GUI & left-click on the journal. Note that I can move the journal about in other GUIs (inventory, microscope, decomposer), just not the synthesizer.

**Comment by jakimfett** [comment]
Please review the [Bug Reporting Guidelines](https://github.com/jakimfett/Minechem/wiki/Bug-Reporting) and update your ticket with the required info.

**Comment by StrangeThistle** [comment]
Tried reverting to forge 10.13.2.1230 (same as in ME4 pack), still crashes in the MultiMC instance when left-clicking on the journal while the synthesizer GUI is open. I can still place the journal in the synthesizer in the ME4 pack, but doing so does not set a recipe.

**Comment by Larandar** [comment]
I do have the same issue, and I think everyone on ME^4 1.0.1/3 will suffer of it.

The journal just do nothing in the synthesizer, and it make crafting a little bit more complex.

**Comment by hilburn** [comment]
@StrangeThistle - that crash is due to not correctly applying Minechem's access transformers. Why it's not doing that, I have no idea, but I assume it's your MultiMC screwing up

**Comment by jakimfett** [comment]
@StrangeThistle, could I get you to try the latest build from the ]Minechem Jenkins](http://jenkins.jakimfett.com/job/Minechem%201.7%20v5/)?

**Comment by StrangeThistle** [comment]
Yeah, I've had nothing but trouble trying to build a 1.7.10 pack in MultiMC. It was just the easiest way I know to try to set up an isolated test. I'll try the new build in the packs in a little bit.

**Comment by StrangeThistle** [comment]
Using build 379 in ME^4 v1.0.4, the journal works as expected. You can call this puppy closed.

**Comment by hilburn** [comment]
schweet

**Comment by jakimfett** [comment]
Awesome, thanks for the fix on this @hilburn, and thanks for reporting it @StrangeThistle!
