### ISSUE TITLE
java.lang.NoClassDefFoundError Existing map can't load 

### ISSUE THREAD

**Issue by jermangarc** [jakimfett/Minechem#614]
Not sure if Minechem can load into existing worlds, so I thought I'd post. I loaded Minechem for the first time into an existing world and it crashes. 

Works fine in a new world. Any help is appreciated. Thanks.

Description: Exception ticking world

java.lang.NoClassDefFoundError: net/minecraft/world/World$2
	at net.minecraft.world.World.func_147460_e(World.java:714)
	at net.minecraft.world.World.func_147459_d(World.java:648)
	at net.minecraft.world.World.func_147444_c(World.java:613)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:488)
	at net.minecraft.world.World.func_147465_d(World.java:466)
	at net.minecraftforge.fluids.BlockFluidClassic.flowIntoBlock(BlockFluidClassic.java:278)
	at net.minecraftforge.fluids.BlockFluidClassic.func_149674_a(BlockFluidClassic.java:139)
	at minechem.fluid.MinechemFluidBlock.func_149674_a(MinechemFluidBlock.java:155)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:391)
	at WorldServerOF.func_147456_g(WorldServerOF.java:477)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183)
	at WorldServerOF.func_72835_b(WorldServerOF.java:234)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by jakimfett** [comment]
Oi, @jermangarc. Thanks for reporting this, is there any chance you could review the [Bug Reporting Guidelines](https://github.com/jakimfett/Minechem/wiki/Bug-Reporting) and update your issue with the required info?

**Comment by jermangarc** [comment]
Thanks for the reply. Here is the information I've gathered. The error log is here http://pastebin.com/8jKgEr2w. 

Yes I know, quite a large modpack, almost a year in the making - not as long developing a mod though ;) (http://www.technicpack.net/modpack/cap-hq). 

The world loads fine without MineChem thus far. When Minechem is loaded and I try to open the world, it crashes out to desktop. I've replicated the problem trying it without MineChem and the world loads fine. Upon further inspection of the startup logs, I found a line towards the end stating "multiple entries with the same key" (http://pastebin.com/hy1XgYL2) line 336. Not sure if it's related.

Like I mentioned before, when I create a new world, it works just fine. This modpack has been put together and config'ed for use on our clan server where Tech and Magic are competing against each other in two different factions. I recently saw a Minechem mod highlight video and thought it would be an excellent addition to the Tech faction. I'm hoping the problem is a simple config fix.

Any help is appreciated, thanks..

**Comment by jakimfett** [comment]
@jermangarc, could I get you to try the latest build from the ]Minechem Jenkins](http://jenkins.jakimfett.com/job/Minechem%201.7%20v5/)?

**Comment by jermangarc** [comment]
Will do! Thanks, I'll let you know my findings.

**Comment by jermangarc** [comment]
Well, it worked! Found out that there is actually a new problem (and probably contributed to the overall problem), but rather running out of ID allocation, but it's only happening on this map. Going to have to figure out how to free up some ID slots so I can continue using this map with Minechem. I opened up the same backup map from September and it worked fine. So it seems that Forge is ignoring any free slots that were previously used, because I know I have plenty of open slots from older mods I've uninstalled. Thanks again for your help.

**Comment by jermangarc** [comment]
Hello jakimfett. Well, after some more testing in my existing world regarding item and block id allocation, I've found that there MIGHT be a problem with how Minechem goes about this process. Let me explain.

I've attached the startup log as well as an excel spreadsheet containing item and block ID dumps that I exported in-game; organized the ID's to show totals between a new world and my existing world; found that the startup log error is a bit confusing on line 99549 - "java.lang.RuntimeException: Invalid id 11105 - maximum id range exceeded".  Looking up this error I found that modders all agree that "too many mods installed". This is why I'm very confused. 

If this is true, then my excel spreadsheet tells me otherwise. In my existing map, I have a total of 11104 ID's used up, which coincides with the RuntimeExeption error of 11105, I GET that. But if you look at the Existing world with New Galacticraft install, the ID's go well over this number to total 11183!? What gives? Do you see my problem? or am I missing something? Any thoughts?

Sorry if I'm being a pain, you don't have to bother if you don't want to, but I'd really love to get this mod in our modpack. Thanks for any help you provide. :)

Log file
https://dl.dropboxusercontent.com/u/72156241/Item-ID-mismatch.txt
Spreedsheet
https://dl.dropboxusercontent.com/u/72156241/item.xlsx
