### ISSUE TITLE
Possible recipe issue?

### ISSUE THREAD

**Issue by finalsliver** [jakimfett/Minechem#622]
Found an item of interest

Rotarycraft, Nether Ore's & Minechem

from what I understand Rotarycraft generates an ingot as the end product for processing "Nether Iron Ore" 
one "Iron Ingot" into a Minechem "Chemical Decomposer" gives 16 "Iron molecules". 
One "Iron molecule" in a Minechem "Chemical Synthesis Machine" gives 1 "Nether Iron Ingot"
9 "Nether Iron Ingot's" make 1 vanilla "Iron Block" which can be broken down into 9 Iron ingots...

Infinite Iron.

EDIT: Reika when asked on Teamspeak pointed in this direction as the probable cause so now I have attacked both of you with this. :dart:

**Comment by hilburn** [comment]
That's very strange - should be 16 elemental iron to make an ingot, will look and see what's going on here

**Comment by hilburn** [comment]
Ok, well.. bug confirmed: 
![image](https://cloud.githubusercontent.com/assets/8307858/6128633/6e867164-b12f-11e4-8368-ca3d849c11bb.png)
I'll have to look a bit deeper about why exactly this is happening though

**Comment by jakimfett** [comment]
This should be fixed in the latest build from the [Minechem Jenkins](http://jenkins.jakimfett.com/job/Minechem%201.7%20v5/).
