### ISSUE TITLE
Decomposer GUI Crash

### ISSUE THREAD

**Issue by parcel31u** [jakimfett/Minechem#626]
Using Version 382

Clicking on the GUI of the decomposer with a chemical, when trying to put it into the slot crashes the game. 

Crash report:
http://pastebin.com/4pWD0ML0

Couldn't send a forge log on pastebin because it was too big >.>

**Comment by parcel31u** [comment]
Seems to be rather clicking the arrow to show recipes which is probably from certain mod items and weird decomposer recipes for them.

**Comment by hilburn** [comment]
Modpack?

**Comment by jakimfett** [comment]
@parcel31u I wasn't able to reproduce this with just Minechem and NEI. Could you please read over the  [Bug Reporting Guidelines](https://github.com/jakimfett/Minechem/wiki/Bug-Reporting) and update your bug report with the specific mod causing this?

**Comment by ScarecrowKrone** [comment]
I can confirm, this crash happened on my server. Someone put milk into a decomposer and crashed the game, crash report here: https://gist.github.com/ScarecrowKrone/1bb515457cab72647502

**Comment by hilburn** [comment]
@ScarecrowKrone - you need to update your Minechem version: `minechem{5.0.5.323}` is what you are running on the server, but the [latest version is 386](http://jenkins.jakimfett.com/job/Minechem%201.7%20v5/) and this bug has been fixed since build 365 in early January

**Comment by hilburn** [comment]
@jakimfett - you should probably remove the outdated tag, the outdated bit doesn't correspond to the original issue that parcel raised

**Comment by jakimfett** [comment]
...whoops. My bad.

**Comment by jakimfett** [comment]
@parcel31u could I get you to grab the latest build from the [Minechem Jenkins build server](http://jenkins.jakimfett.com/job/Minechem%201.7%20v5/) and let me know if this still happens for you?

**Comment by jakimfett** [comment]
Closing due to lack of feedback. Please open a new ticket if this is still an issue.
