### ISSUE TITLE
Penicillin removing effects that shouldn't be removed

### ISSUE THREAD

**Issue by IAA-ShRaPNeL** [jakimfett/Minechem#631]
Penicillin currently removes some effects that shouldn't be able to be removed by normal means, such as Extra- Util flight and Soulfray from Blood magic. 

Forge Version: forge-1.7.10-10.13.2.1277-universal

Minechem Version: MINECHEM-1.7.10-5.0.5.358

**Comment by hilburn** [comment]
Ex-U flight is not actually an issue, and Soul Fray is bugged to allow removal through milk and other potion removal methods

**Comment by jakimfett** [comment]
Should be fixed by https://github.com/jakimfett/Minechem/pull/632

@IAA-ShRaPNeL could I get you to test this with the latest build from the [Minechem Jenkins](http://jenkins.jakimfett.com/view/ForgeModding/job/Minechem%201.7%20v5/)?

**Comment by hilburn** [comment]
Oh @jakimfett - can't test it, the BM potion is bugged and is actually removable

**Comment by IAA-ShRaPNeL** [comment]
Hmm. Milk wasn't removing it.

**Comment by hilburn** [comment]
try a milk bottle

**Comment by IAA-ShRaPNeL** [comment]
I should clarify. Milk Bucket doesn't. Milk Bottle may. I'l report that to MFR.

**Comment by hilburn** [comment]
don't report it to MFR, it's not a bug
