### ISSUE TITLE
Minechem getting stuck on load

### ISSUE THREAD

**Issue by JasonMcRay** [jakimfett/Minechem#637]
The issue I was having (#511) is still present. Its happening every other loading (1 of 2), the Loading is stuck at Registering mod recipes. When I force-kill minecraft and start it again, the loading is fixed. I tried also to start it up with debug mode enabled, but it has been 10 (maybe more) minutes and after time I got a Visual C++ Runtime Error.

Using InfiTech 2 modpack (direct link for download: https://www.dropbox.com/s/r0a3xy0dp0xf9ep/InfiTech%202%20-%202.1.3.zip?dl=0)
Forge 10.13.2.1263
Here is a log I was able to generate before it completely crashed on me: https://www.dropbox.com/s/uekbt2o1nmefizj/fml-client-latest.log?dl=0

**Comment by jakimfett** [comment]
@JasonMcRay could I get you to grab the latest build from the [Minechem Jenkins build server](http://jenkins.jakimfett.com/job/Minechem%201.7%20v5/) and let me know if this still happens for you?

**Comment by JasonMcRay** [comment]
Ok. Will try that during this weekend.

**Comment by jakimfett** [comment]
Closing due to lack of feedback from @JasonMcRay.

**Comment by JasonMcRay** [comment]
Would like to apologize for not replying in here. I was sick for 2 weeks...

Anyway I checked and for second day no freeze on load so far.

**Comment by jakimfett** [comment]
Awesome, thanks for the update! If you run into any other problems, go ahead and open a new bug report.
