### ISSUE TITLE
nei crash 

### ISSUE THREAD

**Issue by kevinbretscher** [jakimfett/Minechem#642]
I am currently playing ftb infinity with pneumatic craft / rotarycraft and minechem 
Every time i use The "u" function in nei The game crashes. 
It seems to happen when i am loading The screen for The decomposer. The game also crashes when i use The "r" key on element like iron or copper.
Maybe it is because it has to run trough many items at once.

(Sorry for my english , i am from The netherlands.)

**Comment by way2muchnoise** [comment]
@kevinbretscher Please add a Crashlog

**Comment by krakentoa** [comment]
I'm playing Material Energy 4, latest release (v.104), with the following modifications:
Minechem-1.7.10-5.0.5.385
fastcraft-1.19
OptiFine_1.7.10_HD_U_B5
Waila-1.5.9_1.7.10
NotEnoughItems-1.7.10-1.0.4.83-universal
CodeChickenCore-1.7.10-1.0.4.35-universal
EnderIO-1.7.10-2.2.8.349
OpenBlocks-1.7.10-1.3
OpenModsLib-1.7.10-0.6
I too have experienced nei-minechem related crashes.
The most recent one occurs when looking up the decomposition of triple compressed cobblestone. The game just hangs; I couldn't get a crash log, I just killed it via the feed the beast launcher button, but not before I copied the game log: http://pastebin.com/pAxqgVQ7
This is reproducible, I have accidentally crashed it once, and repeated the process with success.

**Comment by kevinbretscher** [comment]
i didn't get a crash log either. is there anything else i can do to help?

**Comment by way2muchnoise** [comment]
@kevinbretscher @krakentoa Try turning on the debugMode in the minechem config and post the FML log. That should give us a better look at the problem

**Comment by kevinbretscher** [comment]
where can i find the fml log? in the minecraft folder?

**Comment by way2muchnoise** [comment]
minecraft\logs\fml-client-latest.log

**Comment by kevinbretscher** [comment]
http://we.tl/awCadSGZwz
this is the download for the fml log.

**Comment by krakentoa** [comment]
And here's mine: http://we.tl/OG0ADSoOkZ

**Comment by jakimfett** [comment]
@kevinbretscher and @krakentoa could I get you to grab the latest build from the [Minechem Jenkins build server](http://jenkins.jakimfett.com/job/Minechem%201.7%20v5/) and let me know if this still happens for you?

**Comment by kevinbretscher** [comment]
The game now freezes for about 30 second before giving the recipe but does not crash anymore. :-) 
I tested it with iron/compressed cobble and uranium.

**Comment by krakentoa** [comment]
Weird, compressed cobble decomposes as usual but can't find any NEI recipe (like those which caused the crashes). Just in case here's the log: http://we.tl/u1VlB3oScH
Doesn't crash, which is good enough I guess.

**Comment by kevinbretscher** [comment]
Yes i discovered that too.

**Comment by jakimfett** [comment]
As long as this is no longer crashing, I'm going to close the ticket.
