### ISSUE TITLE
Polytool Sword stat wont increase

### ISSUE THREAD

**Issue by LordIconMC** [jakimfett/Minechem#650]
Addition of Ruthenium or Rhodium will not increase Sword stat
Based on the screenshot you can see both are added and you can also see that i have closed and re-opened the GUI based on the other values being less then 8 
![Imgur](http://i.imgur.com/09ARODw.png)

MineChem 1.7.10-5.0.5.386 (5.0.5)

Additional Mods 
Forge 7.10.85.1230
CodeCicken Core 1.0.4.29
NEI 1.0.3.65
CoFH 3.0.0B9
Ender IO 2.2.8.349

**Comment by hilburn** [comment]
Should be fixed in the latest build
