### ISSUE TITLE
Can you fix this issue I falsely reported to openblocks ?

### ISSUE THREAD

**Issue by crunkazcanbe** [jakimfett/Minechem#651]
They are claiming this error I reported to openblockes is minechems fault .

https://github.com/OpenMods/OpenBlocks/issues/603

**Comment by hilburn** [comment]
Fixed

**Comment by jakimfett** [comment]
@crunkazcanbe go ahead and grab the latest build from the [Minechem Jenkins build server](http://jenkins.jakimfett.com/view/ForgeModding/job/Minechem%201.7%20v5/) for the fix.

**Comment by hilburn** [comment]
@jakimfett you didn't accept the PR on master - ie. the v5 repo...
@crunkazcanbe - can you hold off on updating until he's un-derped
