### ISSUE TITLE
Shears NEI, Decompose Mismatch.

### ISSUE THREAD

**Issue by dngrzone** [jakimfett/Minechem#656]
Placing shears into the Chemical Decomposer makes Promethium.

NEI says it will yield Platinum.

Modpack is Resonant Rise 3.2.3.2 Mainline.

**Comment by way2muchnoise** [comment]
@dngrzone Screenshots? and what is the minechem version?

**Comment by dngrzone** [comment]
Minechem 5.0.5.358 

Youtube link. 
http://youtu.be/eWSQBe_S-TY

**Comment by way2muchnoise** [comment]
@dngrzone Try installing the [latest version](http://jenkins.jakimfett.com/job/Minechem%201.7%20v5/) manualllly

**Comment by jakimfett** [comment]
@dngrzone could I get you to grab the latest build from the [Minechem Jenkins build server](http://jenkins.jakimfett.com/job/Minechem%201.7%20v5/) and let me know if this still happens for you?

**Comment by dngrzone** [comment]
Sorry for the delayed response. I've had a hardware failure and can't load the game right now.

**Comment by jakimfett** [comment]
If this is still an issue @dngrzone, go ahead and open a new ticket.
