### ISSUE TITLE
Energy tab in the machine GUI doesn't render correctly

### ISSUE THREAD

**Issue by akvgergo** [jakimfett/Minechem#657]
![2015-02-14_01 00 12](https://cloud.githubusercontent.com/assets/8812148/6308861/0f05847a-b948-11e4-9c6e-be7b7074236c.png)

The energy values aren't getting displayed.

using the ME^4 modpack version 1.0.4
Minechem version: 5.0.5.364

**Comment by jakimfett** [comment]
Oi, @akvgergo, thanks for the bug report. Any chance you could test the latest build from the [Minechem Jenkins build server](http://jenkins.jakimfett.com/job/Minechem%201.7%20v5/)?

**Comment by akvgergo** [comment]
Of course. I will look into it.

**Comment by akvgergo** [comment]
Same result with 387, the power tab doesn't render the energy values, the help tab shows nothing, and the patreon tab only shows a link.

**Comment by akvgergo** [comment]
ok, so this looks weird. Whenever my EIO magnet is activated, the GUI glitches out.
magnet on:
![2015-02-27_23 06 24](https://cloud.githubusercontent.com/assets/8812148/6422181/f8353d60-bed5-11e4-868d-90b318529e62.png)

magnet off:
![2015-02-27_23 06 15](https://cloud.githubusercontent.com/assets/8812148/6422190/04bfe6c0-bed6-11e4-8b6d-9ceaa193a3ed.png)

Not sure if it's minechem's side or EIO's, so I made an issue at the EIO github too.

**Comment by way2muchnoise** [comment]
@akvgergo That is a good clue now I know where to look it is probably some GL setting that doesn't get reset
