### ISSUE TITLE
Crash on putting elements in the fission reactor with no valid result.

### ISSUE THREAD

**Issue by Xavion3** [jakimfett/Minechem#660]
[The logs are here](http://pastebin.com/iyTPu03S)

This happened via minetweaker, an element that had more than twice the atomic number of any existing element was added and crashes the game upon attempting to put it in a fission reactor. The number that high is wanted so that it can only be gained via decomposing items containing it, unfortunately it crashes if people try.

**Comment by hilburn** [comment]
Sorry - I've been working on v6 for the last few days so haven't really got around to addressing this, but    I'm about to do some v5 fixings and could you provide the MT script you used?

**Comment by Xavion3** [comment]
```
import mods.minechem.Chemicals;
Chemicals.addElement(300, "XX", "TEST", "Other metal", "Solid", "Stable");
```
Just that is enough to cause it, just cheat in the element and then throw it in a powered big reactor. The game freezes up for a second before crashing.

**Comment by jakimfett** [comment]
@Xavion3, question...does it crash when you try to decompose a material that has the element? Or does it crash when you put the chemical into the fission interface? Or both?

**Comment by hilburn** [comment]
@jakimfett - i've identified the problem, fix will happen either tonight or tomorrow

**Comment by jakimfett** [comment]
@Xavion3 could I get you to grab the latest build from the [Minechem Jenkins build server](http://jenkins.jakimfett.com/job/Minechem%201.7%20v5/) and let me know if this still happens for you?

**Comment by Xavion3** [comment]
It works fine now, just sits there and doesn't split as it shouldn't.

**Comment by jakimfett** [comment]
Great, I'll go ahead and close this then.
