### ISSUE TITLE
Radioactive elements in Ender IO filters still decay

### ISSUE THREAD

**Issue by sirius-black9999** [jakimfett/Minechem#674]
when trying to automatically filter out some specific radioactive chemicals to land into a leaded storage box rather than my main storage, in this case polonium, i noticed the item template in the filter slot was still counting down on its decay timer, and once the timer ran out the item in the filter decayed into bismuth. this was using an ender IO filter, and i haven't yet tested whether this works the same way with other kinds of filters yet

**Comment by hilburn** [comment]
Interesting... I'll see what I can do about that when I'm messing with v5 stuff tonight or tomorrow

**Comment by jakimfett** [comment]
@sirius-black9999 could I get you to grab the latest build from the [Minechem Jenkins build server](http://jenkins.jakimfett.com/job/Minechem%201.7%20v5/) and let me know if this still happens for you?

**Comment by mellamokb** [comment]
@jakimfett I am not the OP for this item, but I had this issue as well so just wanted to note that with the latest version (5.0.5.393), I can confirm that the ghost items in an Ender IO filter no longer count down their radioactivity timer.

However the filter items retain the exact countdown as the item you used to set the filter, and so you have to use "Ignore NBT data" to ensure that all versions of the same element with different countdown amounts are properly matched.

**Comment by hilburn** [comment]
@mellamokb yeah there's not much we can do about that - sorry
