### ISSUE TITLE
No userdev jar

### ISSUE THREAD

**Issue by MrabEzreb** [jakimfett/Minechem#675]
I am working on a mod that has compatability for minechem. The minechem api works fine, but if I try to add the actual mod to eclipse, it crashes the game. Could you provide a development jar? Thanks!

**Comment by jakimfett** [comment]
You should be able to work with the existing jarfile by using CodeChickenCore runtime deobfuscation. I don't currently have plans to provide a deobfuscated Minechem v5 jarfile, although you're welcome to submit a pull request adding this functionality to the gradle build process.

Please let me know if using CodeChickenCore doesn't work, and I'll see if I can troubleshoot it.

**Comment by MrabEzreb** [comment]
Alright, I will try it out when I get back home. I haven't uploaded that mod to github yet so I can't work on it at school :(

**Comment by MrabEzreb** [comment]
Also, what does this mean in the readme:
Please note that when running in a dev environment, you'll need to add the following to your VM options:
-Dfml.coreMods.load=minechem.asm.LoadingPlugin

**Comment by way2muchnoise** [comment]
@MrabEzreb It makes the class transformer run in a dev env because we do some ASM on things

**Comment by MrabEzreb** [comment]
alright, thanks

**Comment by jakimfett** [comment]
@MrabEzreb did using CCC work for you?

**Comment by jakimfett** [comment]
Closing due to lack of feedback from @MrabEzreb.
