### ISSUE TITLE
(Crash) Colored wool in the Decomposer - MineChem 5.0.5.387

### ISSUE THREAD

**Issue by Vaygrim** [jakimfett/Minechem#678]
MOD VERSION: MineChem 5.0.5.387
MOD PACK: "Vaygrim's Chance" v1.07a from the AT Launcher (with MineChem added)
FORGE VERSION: 1291

FULL CRASH LOG D/L: https://www.dropbox.com/s/u2l7eqikoktysf4/Minechem_Crash_01.txt?dl=0

ISSUE: I put a stack of Pink Wool into the Decomposer.

(Crashlog removed at the request of @way2muchnoise , cannot post it to Pastebin as it exceeds limits.)

**Comment by way2muchnoise** [comment]
@Vaygrim to start it is the nei handler crashing so I wasn't you putting something in the decomposer but you searching something in nei

**Comment by Vaygrim** [comment]
I had a stack of Pink Wool. Dropped it into the Decomposer, it took 1 of those apart into 'some stuff' but before I could mouse over them the whole thing seized up.

I am not stating it is the Decomposer, factually. I'm stating what I was doing when it happened, factually. (If that makes sense.) I hadn't searched for anything in NEI at the moment of crash. Last thing I searched for was Iron Blocks about 5 minutes before this happened so I could throw down some quick level flooring in a creative test space.

**Comment by way2muchnoise** [comment]
Mayb you clicked the arrow in the decomposer gui that shows all the recipes

**Comment by Vaygrim** [comment]
**Once again.. for clarity:** I had a stack of Pink Wool. Dropped it into the Decomposer and it took 1 of those apart into 'some stuff' but before I could mouse over them the whole thing seized up. Didn't get a chance to interact with anything, didn't get a chance to even move my mouse out from over the 63 Pink Wool still under my pointer. That is exactly when it seized up.

**Comment by way2muchnoise** [comment]
I get what you did but the crash log is screaming nei
````
java.lang.NullPointerException: Updating screen events
	at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:217)
	at minechem.nei.DecomposerNEIRecipeHandler.loadCraftingRecipes(DecomposerNEIRecipeHandler.java:80)
	at codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:465)
	at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:20)
	at codechicken.nei.recipe.TemplateRecipeHandler.transferRect(TemplateRecipeHandler.java:573)
	at codechicken.nei.recipe.TemplateRecipeHandler.access$000(TemplateRecipeHandler.java:33)
	at codechicken.nei.recipe.TemplateRecipeHandler$RecipeTransferRectHandler.transferRect(TemplateRecipeHandler.java:230)
	at codechicken.nei.recipe.TemplateRecipeHandler$RecipeTransferRectHandler.mouseClicked(TemplateRecipeHandler.java:221)
	at codechicken.nei.guihook.GuiContainerManager.mouseClicked(GuiContainerManager.java:329)
````

**Comment by Vaygrim** [comment]
I'm hip, really I am. I'm GLAD that NEI is all over the log.

I'm just telling you what **I** did, and you're telling me "no, you did this most likely". Doesn't really help the issue at hand.

**Comment by way2muchnoise** [comment]
Just FYI I already made something that will probably fix the issue like 45 mins ago (7f2a47141c78cffc626cecf144c8c6d559871ce8). I don't really care what you did to cause it I just wanna see it fixed.

**Comment by jakimfett** [comment]
@Vaygrim any chance you could check if this is fixed in the latest build from the [Minechem Jenkins](http://jenkins.jakimfett.com/job/Minechem%201.7%20v5/)?

**Comment by Vaygrim** [comment]
I'll grab a copy and try to test it some more later tonight.

**Comment by jakimfett** [comment]
@hilburn I wonder if this was related to #626?

@Vaygrim could I get you to grab the latest build from the [Minechem Jenkins build server](http://jenkins.jakimfett.com/job/Minechem%201.7%20v5/) and let me know if this still happens for you?

**Comment by jakimfett** [comment]
@Vaygrim if this is still affecting you, please open a new ticket...closing this due to lack of feedback.
