### ISSUE TITLE
GalactiCraft Cheese Block Decomposer NEI crash 5.0.5.374

### ISSUE THREAD

**Issue by Reddawg99** [jakimfett/Minechem#681]
When browsing the "uses" of a cheese block from Galacticraft in NEI, the section that shows what it decomposes into causes a client crash.

**Comment by jakimfett** [comment]
Please read the [Bug Reporting Guidelines](https://github.com/jakimfett/Minechem/wiki/Bug-Reporting) and update your issue report with the required information.

**Comment by Reddawg99** [comment]
1. Can be repeated.
2. Can be reproduced with just Minechem, NEI and Galacticraft installed.
3. Can't tell you what modpack, because it isn't public yet. But you know that.

Steps to reproduce: Open inventory, search cheese in NEI, right click the cheese block, may need to scroll a bit to get to the decomposer. Instant client crash, no report generated, nothing reported in forge log. Just a instant CTD.

Minechem version 5.0.5.374
GalactiCraft 3.0.8.257
NEI 1.0.4.83

**Comment by way2muchnoise** [comment]
@Reddawg99 Galacticraft planets? Try the [latest build](http://jenkins.jakimfett.com/job/Minechem%201.7%20v5/) you never know. But yeah there is an issue with planets

**Comment by jakimfett** [comment]
@Reddawg99 could I get you to grab the latest build from the [Minechem Jenkins build server](http://jenkins.jakimfett.com/job/Minechem%201.7%20v5/) and let me know if this still happens for you?

**Comment by jakimfett** [comment]
Closing due to lack of feedback from @Reddawg99.
