### ISSUE TITLE
MineTweaker created elements crafted into fire.

### ISSUE THREAD

**Issue by Xavion3** [jakimfett/Minechem#685]
The recipe for 8 chemicals and a bucket always seems to return fire when used with extra elements.

**Comment by way2muchnoise** [comment]
@Xavion3 Well that is interesting also buckets won't be possible since we can't add fluids at runtime

**Comment by Xavion3** [comment]
Sorry, turns out I was wrong. It displays as fire in NEI, when you put the recipe into a crafting table it actually crashes the game. I'd just say make the bug be gone, don't care if you can't add it as a liquid.
 
[Crash Log](http://pastebin.com/zQqu9sMW)

**Comment by hilburn** [comment]
Well we can't add the liquid, as MT registers stuff way after we would be allowed to
