### ISSUE TITLE
GT metatools being counted for decomposition

### ISSUE THREAD

**Issue by Xavion3** [jakimfett/Minechem#686]
As said, GregTech adds a lot of items that use their metatools to be created, for some reason those tools are being counted as ingredients despite not being used up in the crafting causing bizarre looking decomposition results. This is partially exacerbated by the unpredictable components it uses due to the massively different ways of crafting them meaning different tools will give seemingly random metals or tool materials when decomposing, most notably pretty much everything decomposes to have cellulose in it.

**Comment by jakimfett** [comment]
@Xavion3 could I get you to grab the latest build from the [Minechem Jenkins build server](http://jenkins.jakimfett.com/job/Minechem%201.7%20v5/) and let me know if this still happens for you?

**Comment by Xavion3** [comment]
It seems to work now, nothing from my quick checks that was screwing up.

**Comment by jakimfett** [comment]
Awesome, thanks for checking on that!
