### ISSUE TITLE
[Crash][1.7.10] Crash on Decomposer

### ISSUE THREAD

**Issue by nikkimas** [jakimfett/Minechem#691]
Hi, I wanted to put some Iron in the Decomposer, and then I crashed

http://pastebin.com/nAZR7WRF

**Comment by jakimfett** [comment]
Oi, @nikkimas, could I get you to read through the [Bug Reporting Guidelines](https://github.com/jakimfett/Minechem/wiki/Bug-Reporting) and update your bug report?

**Comment by nikkimas** [comment]
Oh, sure. I will read. Just barely looked at the README. hehe. sorry

**Comment by nikkimas** [comment]
Okay, I can't even reproduce. Sorry that I didn't looked it properly up^^.

**Comment by nikkimas** [comment]
Okay, I can't even reproduce. Sorry that I didn't looked it properly up^^.

**Comment by jakimfett** [comment]
No problem, I appreciate it when people submit crash reports!
