### ISSUE TITLE
Crash using EnderIO Fluid Conduit to extract from Chemical Decomposer

### ISSUE THREAD

**Issue by mellamokb** [jakimfett/Minechem#692]
Playing on the latest version of the Material Energy^4 pack, but with MineChem updated to the latest stable version (5.0.5.385). This is a SP world.

I used an EnderIO Fluid Conduit to put 4 buckets of destabilized redstone into the Chemical Decomposer hoping to get some Iron (III) oxide.  However the decomposer doesn't seem to handle any liquids other than water.  So I thought to get my destabilized redstone back I could try pumping back out with the fluid conduit into a drum.  I setup the conduit and it successfully pulls liquid out of the Chemical Decomposer, but when it was about 80% done I crashed.

Here is the crash log: http://pastebin.com/3Sw4Rjtp

I attempted to log back into the world again and it worked fine, and when I checked all the liquid had been successfully drained out of the Chemical Decomposer. So it seems to have just been a temporary problem.

**Comment by jakimfett** [comment]
@mellamokb could I get you to grab the latest build from the [Minechem Jenkins build server](http://jenkins.jakimfett.com/job/Minechem%201.7%20v5/) and let me know if this still happens for you?

**Comment by mellamokb** [comment]
@jakimfett: I can confirm with the latest build (5.0.5.393) there is no longer a crash when piping destabilized redstone in and out of the chemical decomposer.  Thanks!

However it still does not actually process the liquid, not sure if it's expected to or not though.

**Comment by jakimfett** [comment]
Yeah, as long as it's not crashing, I'm going to close this...not really planning to add new features to v5 with v6 in the works.
