### ISSUE TITLE
Limited machine charging rate, even with high capacity power cables

### ISSUE THREAD

**Issue by Sanwi** [jakimfett/Minechem#696]
It's really annoying that machines are limited to 100 RF/t charging rate, even when using high capacity energy conduits such as EnderIO Ender Energy Conduits, or Thermal Expansion Cry-Stabilized Fluxducts. This prevents industrial-scale production, making MineChem pretty much useless for end-game projects.

**Comment by way2muchnoise** [comment]
@Sanwi You can change it in the config file

**Comment by Sanwi** [comment]
Thanks! I didn't know that.
