### ISSUE TITLE
[Feature] Please add enchantment IDs to config file

### ISSUE THREAD

**Issue by SethWilliamson** [jakimfett/Minechem#700]
Please make the enchantment IDs (minechem.potion.PotionEnchantmentCoated) configurable via the config file.

**Comment by jakimfett** [comment]
Out of curiosity...why?

**Comment by SethWilliamson** [comment]
It is mostly an aesthetic request. I was working through the enchantments to resolve some ID conflicts, and in doing so, I was grouping and sorting the effects (Ars Magica Magic Protection with the other Protection effects for example.)

**Comment by jakimfett** [comment]
I'm definitely willing to accept a pull request with this enhancement, but it's not something I'll be prioritizing.

That said, I'll keep it in mind as I work on v6, if we have more than a few enchantment IDs, I'll consider putting them in the config.
