### ISSUE TITLE
Cannot power decomposer

### ISSUE THREAD

**Issue by tikiking1** [jakimfett/Minechem#703]
Tried with Extra Utilities (Furnace Generator) and with Buildcraft. Neither is able to power the decomposer.

![2015-03-08_17 48 14](https://cloud.githubusercontent.com/assets/4196789/6548082/829ee0aa-c5bb-11e4-819e-c4342aa0f337.png)
![2015-03-08_17 48 16](https://cloud.githubusercontent.com/assets/4196789/6548084/82a1eff2-c5bb-11e4-83c0-11d92c18535a.png)
![2015-03-08_17 48 20](https://cloud.githubusercontent.com/assets/4196789/6548083/82a19bec-c5bb-11e4-96bb-b9d96abc1460.png)

Mods installed:
```
Baubles-1.7.10-1.0.1.10.jar
buildcraft-6.4.1.jar
ChickenChunks-1.7.10-1.3.4.17-universal.jar
CodeChickenCore-1.7.10-1.0.4.29-universal.jar
CodeChickenLib-1.7.10-1.1.3.127-universal.jar
CoFHCore-[1.7.10]3.0.0RC5-207.jar
EnderStorage-1.7.10-1.4.5.27-universal.jar
extrabiomesxl_1.7.10-3.16.0.jar
extrautilities-1.2.1.jar
Flans Mod-1.7.10-4.9.0.jar
ForgeMultipart-1.7.10-1.1.1.320-universal.jar
industrialcraft-2-2.2.677-experimental.jar
InventoryTweaks-1.58-147.jar
ironchest-1.7.10-6.0.62.742-universal.jar
Mantle-1.7.10-0.3.2.jar
Minechem-1.7.10-5.0.5.385.jar
ModularPowersuits-0.11.0.178.jar
MrTJPCore-1.7.10-1.0.5.11-universal.jar
mystcraft-1.7.10-0.11.0.00.jar
natura-1.7.10-2.2.0.1.jar
NBTEdit_1.7.10.jar
NEIIntegration-MC1.7.10-1.0.7.jar
NotEnoughItems-1.7.10-1.0.3.74-universal.jar
Numina-0.4.0.100.jar
OpenComputers-MC1.7.10-1.5.2.9-universal.jar
OptiFine_1.7.10_HD_B5.jar
ProjectRed-1.7.10-4.5.14.66-Base.jar
ProjectRed-1.7.10-4.5.14.66-Compat.jar
ProjectRed-1.7.10-4.5.14.66-Integration.jar
ProjectRed-1.7.10-4.5.14.66-Lighting.jar
ProjectRed-1.7.10-4.5.14.66-Mechanical_beta.jar
ProjectRed-1.7.10-4.5.14.66-World.jar
resonant-engine-3.3.0.433-core.jar
resonant-induction-0.3.5.301-core.jar
ShadersModCore-v2.3.28-mc1.7.10-f.jar
Somnia-1.3.0.15.jar
TConstruct-1.7.10-1.8.2a.jar
Thaumcraft-1.7.10-4.2.3.4.jar
ThaumicTinkerer-2.5-1.7.10-162.jar
worldedit-forge-mc1.7.10-6.0-beta-01.jar
WR-CBE-1.7.10-1.4.1.9-universal.jar
```

**Comment by hilburn** [comment]
Extra Utilities 1.2.1 does not correctly recognise RF Receivers due to a derp on RWTema's part - you can either update to extra utilities 1.2.2 or you can download [this mod](http://minecraft.curseforge.com/mc-mods/228105-extra-fixes) which fixes the issue

The buildcraft redstone engine does not output RF.

Basically both are working as intended and this is not an issue

**Comment by tikiking1** [comment]
Okay, updated and it works. Thanks!
