### ISSUE TITLE
Improved Synthesis

### ISSUE THREAD

**Issue by Moorleiche2k** [jakimfett/Minechem#705]
Hey,
while tinkering with decomposing and synthesis of stuff i realized (maybe i am wrong) that there is no way of reserving input slots for chemicals. 
I am not in front of my PC, so excuse if the wording is wrong, but still...
E.g. you want to synthesize Methylacrylat one needs Methyl, Carbon and Oxygen. If you dont put exactly the correct amounts of Chemicals in the input of the Synthesizer, its inventory overflows after a time. 
1. [Basic Request] It would be nice to reserve input slots for certain chemicals and also the amount necessary to craft the chemical.
2. [Advanced Request] Also, it would be nice to have tabs to fabricate several recipes in one synthesizer with priority. For example first Methyl, then Methylacrylate. For this, it would be convenient to provide an option to tell the machine wether to output items in the item-pipe system or output its synthesized chemicals directly into its input.
3 [Advanced Request] Additionally speed upgrades and energy storage upgrades to increase the production would be awesome. Maybe similar to EnderIOs' or IC2s' upgrade system, but defintily non-linear for more then obvious balance reasons.

i am not sure wether the restriction is intentional, but there are already automation options via AE2, but they are not quick but dirty ;) 

Ps.: I am going to edit the wording when i am back at my Home PC. But i guess, its obvious what i am talking about.
Best regards

**Comment by hilburn** [comment]
I'm just gonna say that despite these being nice things (although I don't agree with the whole "make it easy to automate" thing - it should be a challenge) they would all require massive rewrites in how the synthesiser works - to the point where almost all existing code would have to be scrapped.

Also speed upgrades would be pointless, the Synthesiser crafts as soon as you pull from it

**Comment by Moorleiche2k** [comment]
The automatisation request was just an addition, nothing of importance. I personally prefer also to have difficulties that ihave to solve. In other words, there might be people who would like to have such features (actually i know some). But i can understand you.
The request for reserving slots is of more importance, since it forces one to use certain modes. So this is of more importance and, assumingly, could be implemented without a huge effort.
I would offer my help, since i have a certain amount of object-oriented (script) languages, but i stupdily dont have the time since i am doing my master thesis the next days. Still, if its ok for you, i would check if i could support you with it anyhow (at least if wished).
Still, Minechem is nice as it is and i am curious of further development.

**Comment by hilburn** [comment]
Reserving slots really isn't feasible as far as I can tell - I looked into it a while ago and it really is a major rewrite.

Processing happens as soon as you try to extract the output - provided you have the input it will let you extract it - kinda like a crafting bench, except it uses power.

**Comment by jakimfett** [comment]
@Moorleiche2k as of a bit ago, we're not doing any additions to the v5 codebase, instead we're focusing all our efforts on building v6.

Minechem v6 is a complete rewrite of the chemical system. I post updates on the development progress to my [Patreon supporters](https://www.patreon.com/jakimfett) and (less frequently) on Twitter.
