### ISSUE TITLE
[Botania] Crash when looking up used-in recipes for the Terra shatterer

### ISSUE THREAD

**Issue by AlfieSR** [jakimfett/Minechem#709]
[Also mentioned on the Botania github](https://github.com/Vazkii/Botania/issues/647), this issue for some reason affects the Terra Shatterer and *only* the Terra Shatterer, MineChem does not attempt to read recipe data for any of it's ingredients, but the Terra Shatterer appears in the decomposition recipe gui with nothing underneath before shortly freezing the client indefinitely.

**Comment by way2muchnoise** [comment]
@AlfieSR no crash log? Also try turning on debug mode for minechem and post the log (regular one not the crash log)

**Comment by AlfieSR** [comment]
There's no crash log because the game hangs rather than crashing. It never closes itself unless done so by the user, and no errors appear in console. The resulting log file from turning on debug mode and attempting to view the recipe is too large for pastebin so i've put it on my dropbox.

https://www.dropbox.com/s/uhzjvfxkvj54u0f/techniclauncher_2015-03-17.log?dl=0

**Comment by hilburn** [comment]
Just to check - @AlfieSR you are plying with the latest release right? as a similar issue was fixed about 2 weeks ago now

**Comment by AlfieSR** [comment]
I am playing with the latest release available on Curseforge or the Github releases page.
Minechem-1.7.10-5.0.5.358.jar
Is there a newer location to get the latest downloads besides that those listed in the github description?

**Comment by way2muchnoise** [comment]
@AlfieSR you can get it from [Jenkins](http://jenkins.jakimfett.com/job/Minechem%20v5%20for%201.7.10/)

**Comment by AlfieSR** [comment]
Ah, yeah, this issue has been fixed then.
