### ISSUE TITLE
Reactors accept very little RF/t

### ISSUE THREAD

**Issue by Brycey92** [jakimfett/Minechem#715]
Although many mods can carry very large amounts of power through their cables, and a certain duct in Thermal Dynamics can carry infinite RF/t, Minechem reactors only accept a small amount of RF/t per connection. Thus, we have to blanket sides of our reactors with cables to get any sort of reasonable processing rate.

I am running Minechem 5.0.5.393. This has not been tested in single-player or outside of my modpack. I have also not tested build 394, since it has no associated changelog, commit log, or any sort of notes about it.

I don't believe this issue has to do with the other mods in my pack, but if you want me to try to reproduce this issue with Minechem and TE/TD/CoFH Core as the only mods, just ask, and I will do it when I have the time.

**Comment by way2muchnoise** [comment]
@Brycey92 You can change the general accept rate for machines in the config file. Although maybe we should consider adding an extra multiplier to the reactors @jakimfett ?

**Comment by jakimfett** [comment]
I'll keep this in mind when we start looking at multiblocks for v6, but since there's already a way to adjust this, I'm going to say we're not going to change it for v5.
