### ISSUE TITLE
Crash while using Minechem items/machines

### ISSUE THREAD

**Issue by DesecrationGaming** [jakimfett/Minechem#717]
I have had minechem in my personal mudpack for a while and today it started to crash a lot, despite me using it before, I don't know if it is related to the fact that I added mekanism or removed magical crops/ender IO. The first and second crash occurred when I was using the microscope, the third crash occurred when I was looking in the journal and I was typing.

The crash reports can be found on my minecraftforum.com thread in the spoiler tabs here: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/mods-discussion/2402330-minechem-crashing-game

**Comment by jakimfett** [comment]
If adding something started causing crashes, the logical step would be to remove that thing and see if you're still crashing.

Please take a quick read through the [Bug Reporting Guidelines](https://github.com/jakimfett/Minechem/wiki/Bug-Reporting) and verify if this is actually a Minechem bug.

**Comment by jakimfett** [comment]
@DesecrationGaming if this is still happening, please provide the requested information. Closing this due to lack of response, I'll re-open it if I get a response of some kind.
