### ISSUE TITLE
Unable to update world

### ISSUE THREAD

**Issue by Lavaflow** [jakimfett/Minechem#722]
I was doing a general mod update on my homebrew modpack, in which I did not updaye minechem, but did update to forge .1369 (from .1291 but likely irrelevant). At this point my world did not load. It started to, but then went back to main menu, and when I closed it I still had to end the javaw process in my task manager. No crash report was produced, but the log had some hints towards the Thermal Expansion fluid transposer. I had updated TE, so I tried reverting, to no change.  I tried reverting to .1291, but was told minimum forge version was .1360, which I then got. When I tried to load my world with that, I got a crash report in which the only 2 mods mentioned were Thermal Expansion (the fluid transposer) and Minechem.
 I went to the Jenkins to update Minechem (from 5.0.5.394 to 5.0.5.395), but in both forge .1360 and .1369 I was told about missing minechem items (mostly the chemical fluids, I think), and then a crash, in which Thermal Expansion, Ender Storage (codechicken), and Mekanism all were identified in a |java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid| error. 
From here I have tried 9 world loading scenarios:

With no Minechem at all:
New world: successful load
Old world where no Minechem items (other than worldgen) have been created: success
Old World where I used Minechem: Error as above

With Minechem 5.0.5.395:
New world: Did not work once, then worked after that.
Old world where no Minechem items (other than worldgen) have been created: success
          note: This was the same world as I tested before without Minechem, so it may have worked because any problems were deleted then remade. I vaguely recall trying this world before I removed minechem and got the crash, but consider it unconfirmed.
Old World where I used Minechem: Error as above

With Minechem 5.0.5.394
No successful loading of any of the three worlds (New, old with no minechem use, old with minechem use)

If you want I can do a full revert of mods before I updated today to try to load the world to see if there's anything specific I can see regarding minechem fluids in storage, but off the top of my head I had no minechem fluids in the world, tanks, or machines, one each of the microscope, chemical synthesis machine, and chemical decomposer (all three empty), and some amount of minechem items (including chemicals) in my AE system.

It's entirely possible the problem isn't Minechem, but given that I'm told I have 207 mods active on the main menu and my missing item list is apparently 855 and the shown ones all start with minechem.fluid (or CHEMICALID.minechem.fluid or something), it's at least a starting point.

**Comment by jakimfett** [comment]
The important bit was actually the bit you thought was irrelevant. Minechem is build against Forge 10.13.2.1291, because versions later than this implement what a bunch of changes to how fluids are handled.

To fix this, either update to Minechem build 395+ (which may be unstable, you have been warned...), or revert back to a supported version of Forge.
