### ISSUE TITLE
When I installed MineChem I crashed. Why?

### ISSUE THREAD

**Issue by hawk6242** [jakimfett/Minechem#723]
http://pastebin.com/308dwaV2

There is the crash report. Hope this helps.

**Comment by jakimfett** [comment]
You're using an unsupported, bleeding edge, development version of Forge. 

Please revert to the recommended Forge version (currently 10.13.2.1291), or download a Minechem development build from the Minechem Jenkins server (may contain bugs).

**Comment by hawk6242** [comment]
Ok I'll try
