### ISSUE TITLE
[19:10:14] [Client thread/ERROR] [FML/]: The fluid registry is corrupted. A fluid minechem.fluid.FluidElement mt is not properly registered. The mod that registered this is broken

### ISSUE THREAD

**Issue by Kazzamkablam** [jakimfett/Minechem#730]
http://www.filedropper.com/fml-client-latest214

Got that error with latest version of forge when I tried to create new world with Minechem installed.

**Comment by Kazzamkablam** [comment]
nevermind, caused by dev version of forge.

**Comment by way2muchnoise** [comment]
@Kazzamkablam if you get the latest build from the [Jenkins](http://jenkins.jakimfett.com/job/Minechem%20v5%20for%201.7.10/) than it will work with forge 1355+
