### ISSUE TITLE
Minechem loads normally, then after 5 seconds it crashes.

### ISSUE THREAD

**Issue by drago15243** [jakimfett/Minechem#731]
I have only minechem, and forge (10.13.2.1291)
here is the crash:  http://pastebin.com/Ytd5PMf1
I think there is multiple things causing it, is there a config causing it?

**Comment by way2muchnoise** [comment]
@drago15243 Try downloading a fresh copy of the mod? Also any other mods installed?

**Comment by drago15243** [comment]
Reinstalling it did not help and I have no other mods, do I need any?

**Comment by jakimfett** [comment]
Minechem requires CoFHLib (or CoFHCore)...this requirement is listed on all the download pages.

**Comment by drago15243** [comment]
ok thanks, i'm stupid.

**Comment by jakimfett** [comment]
Not stupid, you just didn't read the directions. It's not a crime to miss something. :-P
