### ISSUE TITLE
Crashes in my modpack when i put it in.

### ISSUE THREAD

**Issue by drago15243** [jakimfett/Minechem#733]
Without it the modpack it works fine, so I think it's because of minechem.
crash report:http://pastebin.com/E6yRFaC0

**Comment by way2muchnoise** [comment]
@drago15243 Forge 1355+ requires a special build you can get it from the [Jenkins](http://jenkins.jakimfett.com/job/Minechem%20v5%20for%201.7.10/) it is the latest

**Comment by jakimfett** [comment]
You're using an unsupported, bleeding edge, development version of Forge.

Please revert to the recommended Forge version (currently 10.13.2.1291), or download a Minechem development build from the Minechem Jenkins server (may contain bugs).
