### ISSUE TITLE
Regeneration Bug with Ars Magica 2

### ISSUE THREAD

**Issue by KananaPancake** [jakimfett/Minechem#743]
I had created a private modpack a little while ago which included two other large mods along with MineChem: Ars Magica and Blood Magic.  I thought that having the MineChem Penicillin would assist my Blood Magic endeavors with the Regeneration IV.  However I came across a bug/conflict with the Regeneration in that it would apply Regen, but of a different kind.  This one had a green plus sign on the heart and didn't act like normal Regen with the fast health gain.  After some testing I found that the sole cause was with Ars Magica 2(Removing it resolved the issue and having it with MineChem only caused it again). I am currently using all most updated versions (as of April 27, 2015).  I hope that this issue is resolvable as the Regen not working isn't a necessity but is a pretty nice help with BM. If any addition information is wanted and can be provided, I would be happy to oblige.

**Comment by hilburn** [comment]
The regeneration effect applied is the registered regeneration potion effect. It sounds like AM2 overrides this, you could check by drinking a normal regen potion, and if so would be something you need to bring up with them

**Comment by yarma92** [comment]
It sounds like it is applying the AM2 regeneration spell not the potion effect which is separate last I played with AM2. Also @KananaPancake Blood Magic applies hunger to you when you have the regen potion effect to make spamming it at the altar not as potent.

**Comment by jakimfett** [comment]
Given the complexity of trying to fix this on our side, I'm going to make the call that we're not going to fix this. We'll watch for issues with this as we develop v6 though, thanks for reporting this!

**Comment by KananaPancake** [comment]
No problem, I'm glad to see this was able to reach the developer!
