### ISSUE TITLE
[request] Decomposition of Fantasy Metals from Metallurgy4

### ISSUE THREAD

**Issue by donqixot** [jakimfett/Minechem#746]
Could you create decomposition recipes for Fantasy Metals from Mettalurgy4? Prometheum recipe already exists, but if you could invent recipes for deep iron, infuscolium, carmot, mithril, rubracium, that would be awesome! I realize these are fantasy metals, not real, but some creative minds sure can come up with some interesting ideas?

**Comment by jakimfett** [comment]
It's actually possible for you to do this via Minetweaker. I recommend taking a look at [the example script](https://github.com/jakimfett/Minechem/blob/master/scripts/Minetweaker.zs), and several of @parcel31u's modpacks (specifically Material Energy Hypercubed) make extensive use of Minetweaker scripts to add custom decomposition.

Given that it's already possible to do this, and that Minechem v5 is currently under a feature freeze while we work on v6, we won't be adding in-code support specifically for Metallurgy 4.
