### ISSUE TITLE
Fusion Chamber Speed

### ISSUE THREAD

**Issue by aetherpirate** [jakimfett/Minechem#749]
Not a bug, but an observation / request.

Running build 394. Combining Osmium with Lithium to make gold. Works, but is slow. Bottleneck is stuffing enough power into the reactor. I have plenty (Induction Matrix, 2TJ stored, top tier provider, power sent to reactor via tesseract). Each operation takes 7900RF, but it can't get power fast enough to move quickly. Can this be sped up by allowing the reactor to accept RF more quickly? Perhaps with some sort of power efficiency penalty?

BTW, this is an awesome mod, having much fun experimenting.

**Comment by way2muchnoise** [comment]
@aetherpirate the amount of accepted power per tick can be changed in the config or you can put more cables on it

**Comment by aetherpirate** [comment]
Thanks, I'll try that. Appreciate the fast reply. 

John C.
