### ISSUE TITLE
Configurable Enchantment IDs?

### ISSUE THREAD

**Issue by Amaxter** [jakimfett/Minechem#751]
I get a crash with Cauldron due to an enchantment ID conflict in 5.0.5.395: http://hastebin.com/lomulumude.coffee
Any chance of configurable enchantment ID's becoming a thing?

**Comment by Amaxter** [comment]
Sorry to bump, but I would really love to use Minechem on our public servers with Cauldron and would love to hear any word on this, thank you.

**Comment by DrZed** [comment]
Would be smart so I'm pretty much bumping this as well :P
Then again I make everything in my mods configurable the least you could do is make your IDs configurable Jakim/Noise

**Comment by jakimfett** [comment]
The focus of development is on v6 right now, not on developing new features/functionality. 

You're more than welcome to submit a PR with this functionality, @DrZed, given your vast experience with making mods configurable it should be pretty simple.

**Comment by DrZed** [comment]
Fair enough I'll do so :D Did you know I once worked on minechem having mandrake push things for ya :P I may do it again XD
