### ISSUE TITLE
Posting to curseforge.

### ISSUE THREAD

**Issue by Claycorp** [jakimfett/Minechem#759]
When posting to curseforge the way you tag the file matters.
Someone using the cursevoice client by default will only download the Release versions of mods.

Currently you have a fix for a major liquid issue marked as beta thus people will still download the old version with the bug and likely report it again. I highly suggest marking this build as release so people download that file instead.

**Comment by jakimfett** [comment]
That was done intentionally. The "major liquid issue" ONLY affects people using an unsupported, bleeding edge, development version of Forge.

If people are specifically setting the "I want bleeding edge versions of Forge" option, they're more than capable of setting the "I want bleeding edge versions of Minechem" option, or they can revert to the recommended Forge version (currently 10.13.2.1291) and use the official supported Minechem release.

**Comment by Claycorp** [comment]
Well again with the curse client it doesn't mark version as anything. It just put the latest version of whatever minecraft you pick.

With forge updating around the corner i wouldn't be surprised if more people update forge to these builds.

**Comment by jakimfett** [comment]
People are welcome to update to the newer builds of Minechem, but I will not be setting it as the recommended build until Forge has a recommended build with the fluid changes.

**Comment by Claycorp** [comment]
Understandable. Just going to say that people are likely going to report the fixed issue again as that build will not show up for the normal user.

**Comment by jakimfett** [comment]
If you'll look at the list of closed issues, about half of them in the past month or two are related to the fluid registry changes. I'm very (painfully) aware that my stance on this results in more people reporting the same "bug", when in reality it's (yet another case of) user error.

**Comment by Claycorp** [comment]
Just letting you know that forge 1448 is recommended for 1.7.10 now.
