### ISSUE TITLE
[V6_Dev_Related] Aromatic rings not rendering correctly? 

### ISSUE THREAD

**Issue by MFernflower** [jakimfett/Minechem#761]
The image for aspirin included in minechem shows a cyclohexane ring instead of a benzene ring: 

![ef8iefgif](https://cloud.githubusercontent.com/assets/3164942/8022037/87100278-0c87-11e5-82ee-17f45985fd89.png)

(I may have brought this issue up before but I forgot)

**Comment by MFernflower** [comment]
http://opsin.ch.cam.ac.uk/opsin/acetylsalicylic%20acid.png

**Comment by jakimfett** [comment]
This is waaaaaaayyy beyond my understanding of chemistry. What's it supposed to look like, and how does what we have in the repo differ from what it should look like?

**Comment by MFernflower** [comment]
Well it should look like this: https://en.wikipedia.org/wiki/Aspirin#/media/File:Aspirin-skeletal.svg

**Comment by MFernflower** [comment]
But I also notice the image for anthracene was also messed up

**Comment by jakimfett** [comment]
Ah, so it's an O instead of an OH?

**Comment by MFernflower** [comment]
Also the ring is way diffrent

**Comment by MFernflower** [comment]
If this mod is still being developed, feel free to ask me any O-chem questions.
