### ISSUE TITLE
In the latest jenkin builds some recipes kaput!

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [jakimfett/Minechem#763]
Some recipes I could deconstruct in 398 I can't in build 399. Like chain mail armor for instance. Somebody done fucked up now!

**Comment by RAnders00** [comment]
[Your report is incomplete, please provide more helpful information](https://github.com/jakimfett/Minechem/wiki/Bug-Reporting-Guidelines)

**Comment by hilburn** [comment]
Isn't chain mail armour uncraftable? if so, then it shouldn't be deconstructable. It is possible that another mod added in a real recipe for it, but that might have changed.

Either way, the recipe code is working fine and hasn't been touched between those 2 builds, so it is something else in your environment that has produced this change.

**Comment by jakimfett** [comment]
Closing.
