### ISSUE TITLE
Crash when loading custom modpack. Minechem mentioned frequently in crash report. More info--

### ISSUE THREAD

**Issue by MonzterAssassin** [jakimfett/Minechem#767]
Since I have been instructed to do more with this post I'll do so.
==================================================

Minechem Version: 5.0.5.398 | Forge Version: 10.13.3.1408 | Minecraft Version: 1.7.10 | Fastcraft Enabled

A detailed explanation of the crash is that I start crashing in Post Initialization phase and the report points towards Minechem. As the report also states the following mods errored:
- Tinkers' Steelworks
- Hardcore Ender Expansion
- Iguana Tweaks (Not the Tinkers' Tweaks, mind you)

==========================================

Mods I have since removed in favor of others were:
- Ex Nihilo
- Ex Astris Rebirth

==========================================

Here's my log:

http://pastebin.com/4cZGrySA

Could it be possible there's a mod that doesn't accept it and throws an error? Hmmm...

If you want I can throw you a link to the pack's download but I'd need to upload this hotfix for you first.

**Comment by way2muchnoise** [comment]
Forge version? Minechem version?

**Comment by jakimfett** [comment]
Please go read the [Bug Reporting Guidelines](https://github.com/jakimfett/Minechem/wiki/Bug-Reporting-Guidelines) and update your bug report.

**Comment by MonzterAssassin** [comment]
Latest stable minechem, forge 1408. It has worked so much before but I've
began to make my modpack into a completely different one by adding lots of
new and hardcore mods.

**Comment by MonzterAssassin** [comment]
I made it look fancy and complete [hopefully] yay

**Comment by MonzterAssassin** [comment]
After removing Hardcore Ender Expansion it now says Minechem has an error too. So in the previous reports you'd notice minechem successfully post-initialize. This is the same report but now the errored mods are as follows:
Minechem
OmniWrench2
Tinkers' Steelworks
Iguana Tweaks

Will keep trying to pinpoint the mod though.

**Comment by MonzterAssassin** [comment]
Here is something that intrigued me. A fellow posted something on your Minechem v5 MCF post and nobody took notice to it, and I have bumped it. But for ease of access here's his crash report I put into a pastebin.

http://pastebin.com/4QUrAJ29

**Comment by MonzterAssassin** [comment]
Wait I found it! Your mod is incompatible with the TerraFirmaCraft mod. Not a big deal I'll just remove TFC but just so you know you should make note of that. There's no way to make it compatible because from what I can tell TFC makes base edits to minecraft. Might be something you wanna put in the OP of your thread / on your website for future reference...
