### ISSUE TITLE
Fluid Registry Corruption

### ISSUE THREAD

**Issue by Pyro213** [jakimfett/Minechem#768]
Whenever I attempt to load a game that I have already been in, I crash with the error that the fluid registry is corrupted. it doesn't matter what other mods are installed, it still happens.  Also epic mod, good work my friend

**Comment by way2muchnoise** [comment]
Minechem version? Forge version?

**Comment by Pyro213** [comment]
Any version of both.  Dead serious

On Thursday, June 25, 2015, way2muchnoise <notifications@github.com> wrote:

> Minechem version? Forge version?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jakimfett/Minechem/issues/768#issuecomment-115248379>.
>


-- 
Signed as "A Gentleman and a scholar...and a friend to small animals" (John
Hooten),
Andrew Larson

**Comment by manaziraman** [comment]
True. Same for me. I created a server with Minechem. I used Forge Modloader. I couldn't create a world as it would constantly crash. On the crash report it said Fluid Registry is Corrupted. I really love this mod and now I can't create a world

**Comment by jakimfett** [comment]
I can almost guarantee this is an issue with the new Forge fluid system. 

Try using the recommended version of Forge (currently 10.13.4.1448) and the beta version (labled "Fluid Update") of Minechem [from CurseForge](http://minecraft.curseforge.com/mc-mods/73373-minechem).

If that doesn't fix it, then we can talk.

**Comment by Pyro213** [comment]
Ok thanks my friend

On Thursday, June 25, 2015, jakimfett <notifications@github.com> wrote:

> I can almost guarantee this is an issue with the new Forge fluid system.
>
> Try using the recommended version of Forge (currently 10.13.4.1448) and
> the beta version (labled "Fluid Update") of Minechem from CurseForge
> <http://minecraft.curseforge.com/mc-mods/73373-minechem>.
>
> If that doesn't fix it, then we can talk.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jakimfett/Minechem/issues/768#issuecomment-115456591>.
>


-- 
Signed as "A Gentleman and a scholar...and a friend to small animals" (John
Hooten),
Andrew Larson

**Comment by Pyro213** [comment]
Is the new fuild system to accommodate the 1.8 changes to block and item
metadata?

On Thursday, June 25, 2015, Andrew Larson <alarson2016@gmail.com> wrote:

> Ok thanks my friend
>
> On Thursday, June 25, 2015, jakimfett <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> I can almost guarantee this is an issue with the new Forge fluid system.
>>
>> Try using the recommended version of Forge (currently 10.13.4.1448) and
>> the beta version (labled "Fluid Update") of Minechem from CurseForge
>> <http://minecraft.curseforge.com/mc-mods/73373-minechem>.
>>
>> If that doesn't fix it, then we can talk.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jakimfett/Minechem/issues/768#issuecomment-115456591>
>> .
>>
>
>
> --
> Signed as "A Gentleman and a scholar...and a friend to small animals"
> (John Hooten),
> Andrew Larson
>
>

-- 
Signed as "A Gentleman and a scholar...and a friend to small animals" (John
Hooten),
Andrew Larson

**Comment by jakimfett** [comment]
@Pyro213 @manaziraman sooo...are you still having this issue?

**Comment by Pyro213** [comment]
No no its working for me now thanks for the help

Signed as "A Gentleman and a scholar...and a friend to small animals" (John
Hooten),
Andrew Larson
