### ISSUE TITLE
crash on world generation

### ISSUE THREAD

**Issue by Quack430** [jakimfett/Minechem#773]
every time i try and open a world the game just closes, if i open a world made before i installed then it will make it for a few seconds but then it crashes again.  as far as i know the only mods i'm using is minechem, and cofhcore. http://pastebin.com/yf3iwjG2

**Comment by AegisLesha** [comment]
The same thing happened to me, it seems that MineChem, or another mod, is getting messy with the FluidRegistry

Here's my crashlog: http://pastebin.com/uuDBd2KY
