### ISSUE TITLE
Ghost items "decomposing" in servo's etc.

### ISSUE THREAD

**Issue by Hiranus** [jakimfett/Minechem#777]
I wanted to build nether star generator and i found interesting bug. if you place radioactive element in servo and wait for it to decay (its ghost item) it will change into element with 1 lower number. This changes itemduct network bechavior. I didn't test it, but i suspect that it works like that in all tubes etc that transport items.

**Comment by way2muchnoise** [comment]
@Hiranus Version of minechem?

**Comment by Hiranus** [comment]
Minechem-1.7.10-5.0.5.395

hmm i guess i'm 4 versions behind. Ill update and check this again

**Comment by way2muchnoise** [comment]
Hmm odd thought @hilburn fixed it in e08a9362074255bf29b5fdaa4702f17bb2b5a4a5

**Comment by Hiranus** [comment]
If i could i would record you video of it. :smile: 
There are also problems with autocrafting radioactive elements with ME network, but thats probably because AE tries to match their nbt, and that will never work.

**Comment by hilburn** [comment]
It works in everything other than TD servos apparently - so it's more their problem

**Comment by jakimfett** [comment]
Given that this is specific to Thermal Dynamics servos, I'm going to call this as a "won't fix". We're focusing on Minechem v6, and minor bugs that would require a complete rewrite of a core feature would take more time than it's worth.
