### ISSUE TITLE
nei crash

### ISSUE THREAD

**Issue by JCBurnside** [jakimfett/Minechem#798]
I just put this in a mod pack and it says that the fluid registry is corrupted.  I can't load in a world now.  I put it into skyfactory 2.  I have tried an older version and have the same problem.

**Comment by way2muchnoise** [comment]
A crash log? (on pastebin or alike)

**Comment by JCBurnside** [comment]
here you go http://pastebin.com/rudPks6j

**Comment by jakimfett** [comment]
@JCBurnside you're using the old, outdated version of Forge with the new, updated version of Minechem. Either download the old Minechem version from [the CurseForge page](http://minecraft.curseforge.com/mc-mods/73373-minechem/), or update Forge.

**Comment by JCBurnside** [comment]
I actually had to go up the versions and that fixed it *shrug* but it is working now.
