### ISSUE TITLE
Blueprint Projector stopped working after moving

### ISSUE THREAD

**Issue by chrisgoodtlc** [jakimfett/Minechem#801]
Bit of a weird one here. Playing using the Yogscast mod with recommend mods running. I set-up the blueprint projector in a room and noticed the Chemical Fusion chamber wouldn't fit. I then removed the blueprint then beat up the blueprint projector to be able to move it. 

I then created a nice new place for the fusion generator. I then replaced the blueprint projector, stuck the blueprint in and nothing was displayed. My wife who plays on the same server was able to see the ghost blocks but they were at the old floor level. Not sure how to get the projector to work again.

**Comment by chrisgoodtlc** [comment]
As far as I can see no error messages were reported.

**Comment by way2muchnoise** [comment]
@chrisgoodtlc Maybe some screenshots? Preferably from both perspectives.

**Comment by chrisgoodtlc** [comment]
@way2muchnoise  we have just tried resetting the server, if it's still busted will get screenshots :)

**Comment by way2muchnoise** [comment]
@chrisgoodtlc Also some versions of all the relevant things

**Comment by chrisgoodtlc** [comment]
@way2muchnoise  Screenshots can be found at http://imgur.com/a/Gxy7b versions of mods are: Minecraft 1.6.4
Yogscast Complete Pack 2.9.3.4 -RR-YOGS
MineChem 5.0.5-RC2

Any other mods you need to know versions of ?

**Comment by way2muchnoise** [comment]
@chrisgoodtlc 1.6.4 isn't really supported any more don't know how much I can do about it. But I might look into it when I have some spare time.

**Comment by chrisgoodtlc** [comment]
@way2muchnoise  that's cool mate. Thanks for looking :)

**Comment by chrisgoodtlc** [comment]
@way2muchnoise  just wanted to say, I'm loving the mod :)

**Comment by jakimfett** [comment]
@chrisgoodtlc Yeah, 1.6.4 isn't really supported...have you considered updating to 1.7.10?
