### ISSUE TITLE
When chisel tones is enabled .. cheats! CHEATS EVERYWHERE!!

### ISSUE THREAD

**Issue by prozacgod** [jakimfett/Minechem#810]
Chisel tones bypasses the default zTones recipes and makes it easy to get any of the base zTones blocks.

Using a ztones tile (just stone) you can turn them into base zTones blocks (0 dmg) and  then break it down into things like iron

Maybe disable ztones recipes if chisel tones is installed?

**Comment by jakimfett** [comment]
This would be a problem to report to the ztones developer, not to me. I'm not comfortable disabling functionality in a different mod.
